//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccountGroupRoutine
    {
        public int ClientAccountGroupRoutineID { get; set; }
        public int ClientAccountGroupID { get; set; }
        public int RoutineID { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
    
        public virtual ClientAccountGroup ClientAccountGroup { get; set; }
        public virtual Routine Routine { get; set; }
    }
}
