//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccountGroupCriteria
    {
        public int ClientAccountGroupCriteriaID { get; set; }
        public int ClientAccountGroupID { get; set; }
        public int ClientAccountGroupCriteriaTypeID { get; set; }
        public string ClientAccountGroupCriteriaCode { get; set; }
        public string ClientAccountGroupCriteriaAlias { get; set; }
    }
}
