//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataPumpEntities : DbContext
    {
        public DataPumpEntities()
            : base("name=DataPumpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientAccountGroup> ClientAccountGroups { get; set; }
        public virtual DbSet<ClientAccountGroupCriteria> ClientAccountGroupCriterias { get; set; }
        public virtual DbSet<ClientAccountGroupCriteriaType> ClientAccountGroupCriteriaTypes { get; set; }
        public virtual DbSet<ClientAccountGroupRoutine> ClientAccountGroupRoutines { get; set; }
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<Routine> Routines { get; set; }
        public virtual DbSet<RoutineTask> RoutineTasks { get; set; }
        public virtual DbSet<RoutineType> RoutineTypes { get; set; }
    }
}
