//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Network()
        {
            this.ClientAccountGroups = new HashSet<ClientAccountGroup>();
        }
    
        public int NetworkID { get; set; }
        public string NetworkName { get; set; }
        public string NetworkCode { get; set; }
        public string NetworkReference { get; set; }
        public string NetworkAlias { get; set; }
        public string EligibilityHeader { get; set; }
        public string EligibilityCode { get; set; }
        public string EligibilityAlias { get; set; }
        public string EligibilityReference { get; set; }
        public string EligibilityDelimiter { get; set; }
        public string EligibilitySenderCode { get; set; }
        public string EligibilitySenderAlias { get; set; }
        public string EligibilitySenderReference { get; set; }
        public Nullable<int> EligibilityPendingDays { get; set; }
        public Nullable<int> EligibilityTerminationDays { get; set; }
        public string ClaimAlias { get; set; }
        public string ClaimPrimary { get; set; }
        public string ClaimSecondary { get; set; }
        public string AccumulatorAlias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAccountGroup> ClientAccountGroups { get; set; }
    }
}
