//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationAddress
    {
        public int OrganizationAddressID { get; set; }
        public int OrganizationID { get; set; }
        public int AddressTypeID { get; set; }
        public string Address { get; set; }
        public string AddressDetail { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public bool PrimaryFlag { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
