//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int PersonnelID { get; set; }
        public int EntityHubID { get; set; }
        public int PositionID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> CeaseDate { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
