//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionGroup
    {
        public int PositionGroupID { get; set; }
        public int PositionID { get; set; }
        public int GroupID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Position Position { get; set; }
    }
}
