//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routine()
        {
            this.ClientAccountGroupRoutines = new HashSet<ClientAccountGroupRoutine>();
            this.RoutineTasks = new HashSet<RoutineTask>();
        }
    
        public int RoutineID { get; set; }
        public string RoutineName { get; set; }
        public string RoutineCode { get; set; }
        public string RoutineDescription { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> NextScheduleDate { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public int ScheduleCycleHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAccountGroupRoutine> ClientAccountGroupRoutines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineTask> RoutineTasks { get; set; }
    }
}
