//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineType
    {
        public int RoutineTypeID { get; set; }
        public string RoutineTypeName { get; set; }
        public string RoutineTypeCode { get; set; }
    
        public virtual RoutineType RoutineType1 { get; set; }
        public virtual RoutineType RoutineType2 { get; set; }
    }
}
