//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineTask
    {
        public int RoutineTaskID { get; set; }
        public int RoutineID { get; set; }
        public string RoutineTaskType { get; set; }
        public string SourceName { get; set; }
        public string DestinationName { get; set; }
        public string RoutineProcedureName { get; set; }
        public string RoutineJobName { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Routine Routine { get; set; }
    }
}
