//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNavigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemNavigation()
        {
            this.SystemFunctions = new HashSet<SystemFunction>();
        }
    
        public int SystemNavigationID { get; set; }
        public int SystemModuleID { get; set; }
        public string SystemNavigationName { get; set; }
        public string SystemNavigationCode { get; set; }
        public string SystemNavigationAlias { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemFunction> SystemFunctions { get; set; }
        public virtual SystemModule SystemModule { get; set; }
    }
}
