//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNotificationRecipient
    {
        public int SystemNotificationRecipientID { get; set; }
        public int SystemNotificationID { get; set; }
        public int EntityHubID { get; set; }
    }
}
