//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemSearch()
        {
            this.SystemSearchParameters = new HashSet<SystemSearchParameter>();
            this.SystemSearchSystemFunctions = new HashSet<SystemSearchSystemFunction>();
        }
    
        public int SystemSearchID { get; set; }
        public string SystemSearchName { get; set; }
        public string SystemSearchCode { get; set; }
        public string SystemSearchAlias { get; set; }
        public string SystemSearchDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemSearchParameter> SystemSearchParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemSearchSystemFunction> SystemSearchSystemFunctions { get; set; }
    }
}
