//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemNotification()
        {
            this.SystemNotificationHistories = new HashSet<SystemNotificationHistory>();
        }
    
        public int SystemNotificationID { get; set; }
        public string SystemNotificationName { get; set; }
        public string SystemNotificationCode { get; set; }
        public string SystemNotificationProfile { get; set; }
        public string SystemNotificationReplyEmail { get; set; }
        public string SystemNotificationSubject { get; set; }
        public string SystemNotificationBody { get; set; }
        public string SystemNotificationBodyFormat { get; set; }
        public string SystemNotificationImportance { get; set; }
        public string SystemNotificationSensitivity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemNotificationHistory> SystemNotificationHistories { get; set; }
    }
}
