//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemDomain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemDomain()
        {
            this.SystemDomainModules = new HashSet<SystemDomainModule>();
        }
    
        public int SystemDomainID { get; set; }
        public string SystemDomainName { get; set; }
        public string SystemDomainTitle { get; set; }
        public string SystemDomainImage { get; set; }
        public string SystemDomainFooter { get; set; }
        public string SystemDomainDefaultAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemDomainModule> SystemDomainModules { get; set; }
    }
}
