//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemFunctionMessage
    {
        public int SystemFunctionMessageID { get; set; }
        public int SystemFunctionID { get; set; }
        public string SystemMessageType { get; set; }
        public string SystemMessageText { get; set; }
        public int SortOrder { get; set; }
    
        public virtual SystemFunction SystemFunction { get; set; }
    }
}
