//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemDomainModule
    {
        public int SystemDomainModuleID { get; set; }
        public int SystemDomainID { get; set; }
        public int SystemModuleID { get; set; }
    
        public virtual SystemDomain SystemDomain { get; set; }
        public virtual SystemModule SystemModule { get; set; }
    }
}
