//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemFunction()
        {
            this.GroupPermissions = new HashSet<GroupPermission>();
            this.SystemFunctionObjects = new HashSet<SystemFunctionObject>();
            this.SystemSearchSystemFunctions = new HashSet<SystemSearchSystemFunction>();
            this.SystemFunctionMessages = new HashSet<SystemFunctionMessage>();
        }
    
        public int SystemFunctionID { get; set; }
        public int SystemNavigationID { get; set; }
        public string SystemFunctionName { get; set; }
        public string SystemFunctionCode { get; set; }
        public string SystemFunctionAlias { get; set; }
        public string SystemFunctionAction { get; set; }
        public string SystemFunctionDescription { get; set; }
        public bool NavigationFlag { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupPermission> GroupPermissions { get; set; }
        public virtual SystemNavigation SystemNavigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemFunctionObject> SystemFunctionObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemSearchSystemFunction> SystemSearchSystemFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemFunctionMessage> SystemFunctionMessages { get; set; }
    }
}
