//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmail
    {
        public int UserEmailID { get; set; }
        public int UserID { get; set; }
        public int EmailTypeID { get; set; }
        public string EmailAddress { get; set; }
        public bool PrimaryFlag { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual User User { get; set; }
    }
}
