//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDTE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhone
    {
        public int UserPhoneID { get; set; }
        public int UserID { get; set; }
        public int PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExtension { get; set; }
        public bool PrimaryFlag { get; set; }
    
        public virtual PhoneType PhoneType { get; set; }
        public virtual User User { get; set; }
    }
}
